server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
     defaultZone: http://localhost:8765/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      #------------
      - id: JWT
        uri: lb://JWT
        predicates:
        - Path=/jwt/**
        filters:
        - StripPrefix= 1
#    consul:
#      host: 172.17.0.2
#      port: 8500
#      discovery:
#        register: true
#        service-name: ${spring.application.name}
#        health-check-path: /actuator/health
#        health-check-interval: 15s
#        tags: open-api-/${spring.application.name}
#        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
